version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sucursales-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    ports:
      - "8000:80"
    networks:
      - sucursales-network
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=sucursales_olap
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - REDIS_HOST=redis

  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sucursales_olap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sucursales-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sucursales-network

networks:
  sucursales-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
